# Generated by Django 2.2 on 2019-04-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_brandmodelserviceitemmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='map_to',
            field=models.IntegerField(choices=[(0, 'Service Item'), (1, 'BrandModelCategoryMap'), (2, 'Symptom')]),
        ),
    ]
